sudo: required
services:
  - docker

before_install:
  - docker build -t m0arcin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run m0arcin/react-test npm test -- --coverage

after_success:
  - docker build -t m0arcin/multi-client ./client
  - docker build -t m0arcin/multi-nginx ./nginx
  - docker build -t m0arcin/multi-server ./server
  - docker build -t m0arcin/multi-worker ./worker
  # Log in to the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push m0arcin/multi-client
  - docker push m0arcin/multi-nginx
  - docker push m0arcin/multi-server
  - docker push m0arcin/multi-
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-398910354857
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
